server {
    listen 8443 ssl http2;
    server_name 192.168.1.40; # Reserved this IP in my IDM setup

    root /var/www/html;  # Used the apache docroot folder since that's where I originally had it runing before I had a nginx conflict with k8s service.
    index webhook.php;   # This is the processing file for accepting JSON input from TradingView's webhook url

    # SSL Certificate Paths
    ssl_certificate /etc/nginx/certs/webhook.crt;  # signed the csr with the IDM
    ssl_certificate_key /etc/nginx/certs/webhook.key;  # Used this command to make the key and csr   "openssl req -new -newkey rsa:2048 -keyout /etc/nginx/certs/webhook.key -out /etc/nginx/certs/webhook.csr

    # Recommended Secure SSL Protocols & Ciphers. The typical cipher crap that no one understands (if you do, however, then you should get out more)
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_ciphers 'ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384';

    # Keep your existing PHP block intact
    location / {
        try_files $uri $uri/ =404;
    }

# This section is what NGinx uses to pass-off the PHP processing the PHP-FPM service... Make sure you have php-fpm.service started
 location ~ \.php$ {
        try_files $uri =404;

        # Ensure this matches your installed PHP version socket path. This path is for Redhat/cent/rocky
        fastcgi_pass unix:/run/php-fpm/www.sock;
        
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }
}
